In [66]:
import pandas as pd

df = pd.read_csv('bank-additional-full.csv', sep=';')
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

In [68]:
df.describe(include='all')

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
count,41188.00000,41188,41188,41188,41188,41188,41188,41188,41188,41188,...,41188.000000,41188.000000,41188.000000,41188,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188
unique,NaN,12,4,8,3,3,3,2,10,5,...,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,2
top,NaN,admin.,married,university.degree,no,yes,no,cellular,may,thu,...,NaN,NaN,NaN,nonexistent,NaN,NaN,NaN,NaN,NaN,no
freq,NaN,10422,24928,12168,32588,21576,33950,26144,13769,8623,...,NaN,NaN,NaN,35563,NaN,NaN,NaN,NaN,NaN,36548
mean,40.02406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.567593,962.475454,0.172963,NaN,0.081886,93.575664,-40.502600,3.621291,5167.035911,NaN
std,10.42125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.770014,186.910907,0.494901,NaN,1.570960,0.578840,4.628198,1.734447,72.251528,NaN
min,17.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000000,0.000000,0.000000,NaN,-3.400000,92.201000,-50.800000,0.634000,4963.600000,NaN
25%,32.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000000,999.000000,0.000000,NaN,-1.800000,93.075000,-42.700000,1.344000,5099.100000,NaN
50%,38.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.000000,999.000000,0.000000,NaN,1.100000,93.749000,-41.800000,4.857000,5191.000000,NaN
75%,47.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.000000,999.000000,0.000000,NaN,1.400000,93.994000,-36.400000,4.961000,5228.100000,NaN
max,98.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56.000000,999.000000,7.000000,NaN,1.400000,94.767000,-26.900000,5.045000,5228.100000,NaN

In [ ]:
for col in df.select_dtypes(include='object').columns:
    print(col)
    print(df[col].value_counts())
    print('----------------')

job
job
admin.           10422
blue-collar       9254
technician        6743
services          3969
management        2924
retired           1720
entrepreneur      1456
self-employed     1421
housemaid         1060
unemployed        1014
student            875
unknown            330
Name: count, dtype: int64
----------------
marital
marital
married     24928
single      11568
divorced     4612
unknown        80
Name: count, dtype: int64
----------------
education
education
university.degree      12168
high.school             9515
basic.9y                6045
professional.course     5243
basic.4y                4176
basic.6y                2292
unknown                 1731
illiterate                18
Name: count, dtype: int64
----------------
default
default
no         32588
unknown     8597
yes            3
Name: count, dtype: int64
----------------
housing
housing
yes        21576
no         18622
unknown      990
Name: count, dtype: int64
----------------
loan
loan
no         33950
yes         6248
unknown      990
Name: count, dtype: int64
----------------
contact
contact
cellular     26144
telephone    15044
Name: count, dtype: int64
----------------
month
month
may    13769
jul     7174
aug     6178
jun     5318
nov     4101
apr     2632
oct      718
sep      570
mar      546
dec      182
Name: count, dtype: int64
----------------
day_of_week
day_of_week
thu    8623
mon    8514
wed    8134
tue    8090
fri    7827
Name: count, dtype: int64
----------------
poutcome
poutcome
nonexistent    35563
failure         4252
success         1373
Name: count, dtype: int64
----------------
y
y
no     36548
yes     4640
Name: count, dtype: int64
----------------

In [70]:
# mô tả chú thích về bộ dữ liệu 
# 1 - age (numeric) 

# 2 - job : type of job (categorical: 'admin.','blue-collar','entrepreneur','housemaid','management','retired','self-employed','services','student','technician','unemployed','unknown') 

# 3 - marital : marital status (categorical: 'divorced','married','single','unknown'; note: 'divorced' means divorced or widowed) 

# 4 - education (categorical: 'basic.4y','basic.6y','basic.9y','high.school','illiterate','professional.course','university.degree','unknown') 

# 5 - default: has credit in default? (categorical: 'no','yes','unknown') 

# 6 - housing: has housing loan? (categorical: 'no','yes','unknown') 

# 7 - loan: has personal loan? (categorical: 'no','yes','unknown') 

# # related with the last contact of the current campaign: 

# 8 - contact: contact communication type (categorical: 'cellular','telephone') 

# 9 - month: last contact month of year (categorical: 'jan', 'feb', 'mar', ..., 'nov', 'dec') 

# 10 - day_of_week: last contact day of the week (categorical: 'mon','tue','wed','thu','fri') 

# 11 - duration: last contact duration, in seconds (numeric). Important note: this attribute highly affects the output target (e.g., if duration=0 then y='no'). Yet, the duration is not known before a call is performed. Also, after the end of the call y is obviously known. Thus, this input should only be included for benchmark purposes and should be discarded if the intention is to have a realistic predictive model. 

 

# other attributes 

 

# 12 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact) 

# 13 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric; 999 means client was not previously contacted) 

# 14 - previous: number of contacts performed before this campaign and for this client (numeric) 

# 15 - poutcome: outcome of the previous marketing campaign (categorical: 'failure','nonexistent','success') 

 

# social and economic context attributes 

 

# 16 - emp.var.rate: employment variation rate - quarterly indicator (numeric) 

# 17 - cons.price.idx: consumer price index - monthly indicator (numeric) 

# 18 - cons.conf.idx: consumer confidence index - monthly indicator (numeric) 

# 19 - euribor3m: euribor 3 month rate - daily indicator (numeric) 

# 20 - nr.employed: number of employees - quarterly indicator (numeric) 

 

# # campaign result 

# 21 - y - has the client subscribed a term deposit? (binary: 'yes','no')

In [71]:
## các cột emp.var.rate ,cons.price.idx,cons.conf.idx,nr.employed  có ký tự đặc biết là .   dễ gây ảnh hưởng đến việc viết code hay sql sau này
def clean_column_names(df):
    import re
    
    df = df.copy()
    
    new_cols = []
    
    for col in df.columns:
        col = col.lower().strip()
        col = col.replace('.', '_')
        col = col.replace(' ', '_')
        col = re.sub(r'[^a-z0-9_]', '', col)
        col = re.sub(r'_+', '_', col)
        new_cols.append(col)

    df.columns = new_cols
    return df
df=clean_column_names(df)
print("After:", df.columns)
# thật ra có mỗi dấu . nhưng viết hàm xử lý một thể các trường hợp luôn

After: Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp_var_rate', 'cons_price_idx',
       'cons_conf_idx', 'euribor3m', 'nr_employed', 'y'],
      dtype='object')

In [72]:
df.isnull().sum()
# dataset này khá là sạch rồi không có null :)) nhưng mà ở đây trong bộ dữ liệu thì là unknown thay cho null

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp_var_rate      0
cons_price_idx    0
cons_conf_idx     0
euribor3m         0
nr_employed       0
y                 0
dtype: int64

In [73]:
(df.eq('unknown').sum() / len(df) * 100).round(2)
# job, marital,education,housing,loan có tỷ lệ unknown nhỏ, trong khi default có tỷ lệ unkonw lớn

age                0.00
job                0.80
marital            0.19
education          4.20
default           20.87
housing            2.40
loan               2.40
contact            0.00
month              0.00
day_of_week        0.00
duration           0.00
campaign           0.00
pdays              0.00
previous           0.00
poutcome           0.00
emp_var_rate       0.00
cons_price_idx     0.00
cons_conf_idx      0.00
euribor3m          0.00
nr_employed        0.00
y                  0.00
dtype: float64

In [ ]:
cols_drop_unknown = ['job', 'marital', 'education', 'housing', 'loan']

for col in cols_drop_unknown:
    df = df[df[col] != 'unknown']

# với tỷ lệ thấp thì drop còn cột default sẽ giữ lại vì nó có thể mang một ý nghĩa nào đấy để phân tích

In [76]:
from sqlalchemy import create_engine

username = "postgres"
password = "nkingd"
host = "localhost"
port = "5432"
database = "databank"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")
                       
                
table_name = "customer"
df.to_sql(table_name,engine,if_exists="replace",index=True)

245